In [5]:
#pip install torch
import torch
import numpy as np

In [2]:
#matrics of zeroes
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [3]:
#matrics of ones
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [4]:
torch.ones(2,2)*3

tensor([[3., 3.],
        [3., 3.]])

In [6]:
w= np.array([6.0,7,9])
w1=torch.from_numpy(w)
torch.ones(2,3)*w1

tensor([[6., 7., 9.],
        [6., 7., 9.]], dtype=torch.float64)

In [10]:
y= np.array([[6],[7]])
y1=torch.from_numpy(y)
torch.ones(2,2)*y1

tensor([[6., 6.],
        [7., 7.]])

In [11]:
#generate matrics of random number
x1=torch.rand(2,3)

In [13]:
x1*y1

tensor([[2.9859, 5.7767, 4.3139],
        [0.8433, 3.6902, 2.3324]])

In [14]:
torch.ones(3,3).mul(5)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

In [16]:
t2= torch.from_numpy(numpy.array([[.2],[4.7],[1.9]]))

In [17]:
z=torch.rand(3,3)

In [18]:
z.mul(z)

tensor([[0.6206, 0.0306, 0.1230],
        [0.8011, 0.0267, 0.1283],
        [0.3973, 0.3051, 0.0810]])

In [20]:
t1= torch.rand(4,5)

In [22]:
# find max in a tensor column 
t1.max(axis=1)

torch.return_types.max(
values=tensor([0.6208, 0.9438, 0.8857, 0.7078]),
indices=tensor([3, 4, 4, 4]))

In [24]:
t1.max(axis=0)

torch.return_types.max(
values=tensor([0.3246, 0.6158, 0.4911, 0.7616, 0.9438]),
indices=tensor([2, 0, 2, 2, 1]))

In [26]:
t1.sum(axis=0)

tensor([0.5842, 1.9105, 0.9751, 1.9338, 2.8213])