In [13]:
#pip install torch
import torch
import numpy

In [10]:
#matrics of zeroes
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [11]:
#matrics of ones
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [22]:
torch.ones(2,2)*3

tensor([[3., 3.],
        [3., 3.]])

In [41]:
w= numpy.array([[6],[7]])
w1=torch.from_numpy(w)

In [43]:
torch.ones(2,2)*w1

tensor([[6., 6.],
        [7., 7.]])

In [42]:
w1

tensor([[6],
        [7]], dtype=torch.int32)