In [13]:
#pip install torch
import torch
import numpy

In [10]:
#matrics of zeroes
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [11]:
#matrics of ones
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [22]:
torch.ones(2,2)*3

tensor([[3., 3.],
        [3., 3.]])

In [51]:
w= numpy.array([6,7])
w1=torch.from_numpy(w)
torch.ones(2,2)*w1

tensor([[6., 7.],
        [6., 7.]])

In [50]:
y= numpy.array([[6],[7]])
y1=torch.from_numpy(y)
torch.ones(2,2)*y1

tensor([[6., 6.],
        [7., 7.]])

In [49]:
#generate matrics of random number
torch.rand(2,3)

tensor([[0.4171, 0.3155, 0.5753],
        [0.6509, 0.3057, 0.3371]])