In [1]:
#pip install torch
import torch
import numpy as np

In [2]:
#matrics of zeroes
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [3]:
#matrics of ones
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [4]:
torch.ones(2,2)*3

tensor([[3., 3.],
        [3., 3.]])

In [6]:
w= np.array([6.0,7,9])
w1=torch.from_numpy(w)
torch.ones(2,3)*w1

tensor([[6., 7., 9.],
        [6., 7., 9.]], dtype=torch.float64)

In [10]:
y= np.array([[6],[7]])
y1=torch.from_numpy(y)
torch.ones(2,2)*y1

tensor([[6., 6.],
        [7., 7.]])

In [11]:
#generate matrics of random number
x1=torch.rand(2,3)

In [13]:
x1*y1

tensor([[2.9859, 5.7767, 4.3139],
        [0.8433, 3.6902, 2.3324]])

In [14]:
torch.ones(3,3).mul(5)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

In [16]:
t2= torch.from_numpy(numpy.array([[.2],[4.7],[1.9]]))

In [17]:
z=torch.rand(3,3)

In [18]:
z.mul(z)

tensor([[0.6206, 0.0306, 0.1230],
        [0.8011, 0.0267, 0.1283],
        [0.3973, 0.3051, 0.0810]])

In [20]:
t1= torch.rand(4,5)

In [22]:
# find max. min, sum in a tensor 
t1.max(axis=1)
t1.max(axis=0)
t1.sum(axis=0)
t1.min(axis=0)


torch.return_types.max(
values=tensor([0.6208, 0.9438, 0.8857, 0.7078]),
indices=tensor([3, 4, 4, 4]))

In [31]:
torch.cat([t2,t2],axis=0)

tensor([[0.2000],
        [4.7000],
        [1.9000],
        [0.2000],
        [4.7000],
        [1.9000]], dtype=torch.float64)

In [30]:
t2

tensor([[0.2000],
        [4.7000],
        [1.9000]], dtype=torch.float64)

In [65]:
data = [[1.7, 2.9],[3.8, 4]]
x_data = torch.tensor(data, dtype=float)

In [66]:
x_data

tensor([[1.7000, 2.9000],
        [3.8000, 4.0000]], dtype=torch.float64)

In [57]:
x_data.device

device(type='cpu')

In [58]:
print(f"Shape of tensor: {x_data.shape}")

Shape of tensor: torch.Size([2, 2])


In [62]:
torch.cuda.is_available()

False

In [86]:
#autograd
x= torch.tensor([2.,8,9],requires_grad=True)
y= torch.tensor([3.,9,0],requires_grad=True)
z= torch.tensor([4.,7,9],requires_grad=True)


func= x**2+y**2+z

In [79]:
func.backward()

In [80]:
x.grad,y.grad,z.grad

(tensor([4.]), tensor([6.]), tensor([1.]))

In [81]:
torch.randn(3)

tensor([ 0.2059,  1.0177, -0.1453])

In [89]:
x1=x*2
print(x1)
z=x1*3

tensor([ 4., 16., 18.], grad_fn=<MulBackward0>)


In [90]:
print(z)

tensor([12., 48., 54.], grad_fn=<MulBackward0>)


In [92]:
z.backward(x1)

In [94]:
x.grad

tensor([ 24.,  96., 108.])

In [95]:
#remove grad
x.requires_grad_(False)
x

tensor([2., 8., 9.])

In [99]:
x=torch.tensor(x, requires_grad=True)

<ipython-input-99-9ad52b287487>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x=torch.tensor(x, requires_grad=True)


In [100]:
with torch.no_grad():
    y=x+2
    print(y)

    
x.detach()

tensor([ 4., 10., 11.])


In [111]:
x= torch.rand(4,3)
w= torch.tensor([2.,3,4], requires_grad=True)
y_ac= torch.rand(1,3)

In [113]:
y_pred= x*w
loss= torch.mean(y_pred-y_ac)**2
loss.backward()
w=w-w.grad*0.001

In [152]:
x= torch.rand(4,3)
w= torch.tensor([2.,3,4], requires_grad=True)
y_ac= torch.rand(1,3)
for epoch in range(100):
    y_pred= x*w
    loss= torch.mean(y_pred-y_ac)**2
    loss.backward()

    with torch.no_grad():
             w-=w.grad*0.001
             #print(w)
    w.grad.zero_()


    if epoch%100==0:
         print(f'loss function is {loss} for {w}')


loss function is 0.31766068935394287 for tensor([1.9999, 2.9998, 3.9998], requires_grad=True)


In [154]:
#use torch.nn
import torch.nn as nn
x= torch.rand(4,3)
w= torch.tensor([2.,3,4], requires_grad=True)
y_ac= torch.rand(1,3)

loss= nn.MSELoss()
optimizer= torch.optim.SGD([w],lr=0.001)
for epoch in range(100):
    y_pred= x*w
    
    l=loss(y_ac,y_pred)
    l.backward()

    optimizer.step()

    optimizer.zero_grad()


    if epoch%100==0:
         print(f'loss function is {loss} for {w}')


loss function is MSELoss() for tensor([1.9998, 2.9996, 3.9990], requires_grad=True)


C:\Users\hasnf\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\loss.py:529: UserWarning: Using a target size (torch.Size([4, 3])) that is different to the input size (torch.Size([1, 3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [162]:
#use nn.linear
import torch.nn as nn
x= torch.rand(4,3)
#w= torch.tensor([2.,3,4], requires_grad=True)
y_ac= torch.rand(1,3)



sample,feature= x.shape
input_features= feature
model= nn.Linear(input_features,1)
loss= nn.MSELoss()
optimizer= torch.optim.SGD(model.parameters(),lr=0.001)
for epoch in range(100):
    y_pred= model(x)
    
    l=loss(y_ac,y_pred)
    l.backward()

    optimizer.step()

    optimizer.zero_grad()


    if epoch%100==0:
        [w,b]=model.parameters()
        print(f'loss function is {l} for {w[0]}')


loss function is 1.1961249113082886 for tensor([-0.1105,  0.3324, -0.0923], grad_fn=<SelectBackward0>)


In [15]:
#linear regression
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [19]:
dt=datasets.load_breast_cancer()

In [21]:
x,y = dt.data, dt.target

In [23]:
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size=0.2)

In [31]:
sc = StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [39]:
x_train= torch.from_numpy(x_train.astype(np.float32))
x_test= torch.from_numpy(x_test.astype(np.float32))
y_train= torch.from_numpy(y_train.astype(np.float32))
y_test= torch.from_numpy(y_test.astype(np.float32))

In [43]:
y_train=y_train.view(y_train.shape[0],1)
y_test=y_test.view(y_test.shape[0],1)

In [53]:
class LogisticRegression(nn.Module):

    def __init__(self,n_input_features):
        super(LogisticRegression,self).__init__()
        self.linear = nn.Linear(n_input_features,1)

    def forward(self,x):
        y_pred= torch.sigmoid(self.linear(x))    
        return y_pred


n_sample, n_feature= x_train.shape

model= LogisticRegression(n_feature)

#loss
criterion= nn.BCELoss()
optimizer= torch.optim.SGD(model.parameters(),0.01)


for epoch in range(100):
      
      y_pred=model(x_train)

      loss= criterion(y_pred, y_train)

      loss.backward()

      optimizer.step()

      optimizer.zero_grad()

      if epoch%10==0:
          print(f'loss is {loss}')


with torch.no_grad():

    y_pred= model(x_test).round()
    acc = y_pred.eq(y_test).sum()/ float(y_test.shape[0])
      


loss is 0.7612061500549316
loss is 0.5893994569778442
loss is 0.4907490611076355
loss is 0.4275832176208496
loss is 0.38355526328086853
loss is 0.35092654824256897
loss is 0.3256283700466156
loss is 0.3053312301635742
loss is 0.28860822319984436
loss is 0.2745365798473358


In [1]:
# dataset and dataloader


In [7]:
#feed forward
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

In [8]:
device= torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [9]:
#hyper parameters
input_size= 784 #28*28
hidden_size= 100
num_classes= 10
num_epochs=2
batch_size= 100
learning_rate= 0.001

In [11]:
#mnist
train_dataset= torchvision.datasets.MNIST(root='./data',train= True,
transform= transforms.ToTensor(), download= True)

#mnist
test_dataset= torchvision.datasets.MNIST(root='./data',train= False,
transform= transforms.ToTensor())

In [16]:
train_loader= torch.utils.data.DataLoader(train_dataset, batch_size=batch_size,
shuffle=True)

In [24]:
examples= iter(train_loader)
samples,labels= examples.next()
samples.shape

torch.Size([100, 1, 28, 28])

torch.Size([100, 1, 28, 28])